name: card_news_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  gal: ^2.3.2
  google_fonts: ^7.0.2
  google_generative_ai: ^0.4.7
  google_mobile_ads: ^7.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
